services:
  messaging-settings-api:
    image: ghcr.io/sundsvallskommun/api-service-messaging-settings:latest
    ports:
      - "8084:8080" 
    environment:
      SPRING_CONFIG_ADDITIONAL_LOCATION: file:/app/application-default.yml
    volumes:
      - ./application-messaging-settings.yml:/app/application-default.yml
    restart: unless-stopped
    networks: 
      - dockernet

networks:
  dockernet:
    external: true 
