services:
  eventlog-api:
    image: ghcr.io/sundsvallskommun/api-service-eventlog:latest
    container_name: eventlog-api
    ports:
      - "8080:8080" 
    environment:
      SPRING_CONFIG_ADDITIONAL_LOCATION: file:/app/application-default.yml
    volumes:
      - ./application-eventlog.yml:/app/application-default.yml
    restart: unless-stopped
    networks:
      - dockernet

networks:
  dockernet:
    external: true 
