spring:
  datasource:
    url: jdbc:mariadb://mariadb:3306/case_management
    username: case_management
    password: case_management
  jpa:
    hibernate:
    ddl-auto: validate
  flyway:
    enabled: true

integration:
  arendeexport:
    url: http://wiremock:8080/byggr
  case-data:
    oauth2ClientId: ignored
    oauth2ClientSecret: ignored
    oauth2TokenUrl: http://wiremock:8080/token
    url: http://case-data-api:8080/
    namespaces:
      2281:
        - "CONTACTSUNDSVALL"
  alk-t:
    oauth2ClientId: ignored
    oauth2ClientSecret: ignored
    oauth2TokenUrl: http://wiremock:8080/token
    url: http://wiremock:8080/alk-t/
  citizen:
    oauth2ClientId: ignored
    oauth2ClientSecret: ignored
    oauth2TokenUrl: http://wiremock:8080/token
    url: http://wiremock:8080/citizen/
  party:
    oauth2ClientId: ignored
    oauth2ClientSecret: ignored
    oauth2TokenUrl: http://wiremock:8080/token
    url: http://party-api:8080/
  fb:
    database: test_db
    password: test_pass
    url: http://wiremock:8080/fb/
    username: test_user
  lantmateriet:
    oauth2ClientId: test_key
    oauth2ClientSecret: test_secret
    oauth2TokenUrl: http://wiremock:8080/token
    registerbeteckning:
      url: http://wiremock:8080/lantmateriet/
  messaging:
    channel: channel
    client-id: ignored
    client-secret: ignored
    token: token
    token-uri: http://wiremock:8080/token
    url: http://messaging-api:8080/
  minutmiljo:
    password: test_pass
    url: http://wiremock:8080/ecos/
    username: test_user
  oep-integrator:
    oauth2ClientId: ignored
    oauth2ClientSecret: ignored
    oauth2TokenUrl: http://wiremock:8080/token
    url: http://oep-inetgrator-api:8080/
