networks:
  dockernet:
    name: dockernet

services:
  mariadb:
    image: mariadb:10.6
    environment:
      MARIADB_ROOT_PASSWORD: root
      TZ: Europe/Stockholm
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "-uroot", "-proot"]
      interval: 5s
      timeout: 3s
      retries: 30
    volumes:
      - mariadb-data:/var/lib/mysql
      - ./db-init.sql:/docker-entrypoint-initdb.d/01-init.sql:ro
    restart: unless-stopped
    networks:
      dockernet:
        aliases:
          - mariadb 

volumes:
  mariadb-data: