services:
  db-seeder:
    image: mariadb:10.6
    networks:
      - dockernet
    environment:
      MARIADB_HOST: mariadb   
      MARIADB_ROOT_PASSWORD: root 
    volumes:
      - ./sql:/seed:ro            
      - ./run.sh:/run.sh:ro      
    entrypoint: ["/bin/sh", "/run.sh"]

networks:
  dockernet:
    external: true