spring:
  datasource:
    url: jdbc:mariadb://mariadb:3306/case_status
    username: case_status
    password: case_status
  jpa:
    hibernate:
    ddl-auto: validate
  flyway:
    enabled: true
  security:
    oauth2:
      client:
        provider:
          case-management:
            token-uri: http://wiremock:8080/token
          eventlog:
            token-uri: http://wiremock:8080/token
          party:
            token-uri: http://wiremock:8080/token
          support-management:
            token-uri: http://wiremock:8080/token
          oep-integrator:
            token-uri: http://wiremock:8080/token
          case-data:
            token-uri: http://wiremock:8080/token
        registration:
          case-management:
            client-id: the-client-id
            client-secret: the-client-secret
          eventlog:
            client-id: the-client-id
            client-secret: the-client-secret
          party:
            client-id: the-client-id
            client-secret: the-client-secret
          support-management:
            client-id: the-client-id
            client-secret: the-client-secret
          oep-integrator:
            client-id: the-client-id
            client-secret: the-client-secret
          case-data:
            client-id: the-client-id
            client-secret: the-client-secret
scheduler:
  eventlog:
    cron: "-"
    name: "eventlog"
    municipalityId: 123
    shedlock-lock-at-most-for: PT10M
    maximum-execution-time: PT10M
    clock-skew: PT5S
cache:
  isprod: false
  scheduled:
    name: "cache_job"
    cron: "-"
    shedlock-lock-at-most-for: PT10M
    maximum-execution-time: PT10M
integration: 
  case-management:
    base-url: http://wiremock:8080/casemanagement
  eventlog:
    base-url: http://eventlog-api:8008/
  oep-integrator:
    base-url: http://wiremock-api:8080/oepintegrator
  party:
    base-url: http://party-api:8080/
  support-management:
    base-url: http://support-management-api:8080/
  case-data:
    base-url: http://case-data-api:8080/
    namespaces:
      - CONTACTSUNDSVALL

  