services:
  case-status-api:
    image: ghcr.io/sundsvallskommun/api-service-case-status:latest
    ports:
      - "8088:8080" 
    environment:
      SPRING_CONFIG_ADDITIONAL_LOCATION: file:/app/application-default.yml
    volumes:
      - ./application-case-status.yml:/app/application-default.yml
    restart: unless-stopped
    networks:
      - dockernet

networks:
  dockernet:
    external: true 
