services:
  templating-api:
    image: ghcr.io/sundsvallskommun/api-service-templating:latest
    ports:
      - "8086:8080" 
    environment:
      SPRING_CONFIG_ADDITIONAL_LOCATION: file:/app/application-default.yml
    volumes:
      - ./application-templating.yml:/app/application-default.yml
    restart: unless-stopped
    networks:
      - dockernet

networks:
  dockernet:
    external: true 
