services:
  relations-api:
    image: ghcr.io/sundsvallskommun/api-service-relations:latest
    ports:
      - "8082:8080" 
    environment:
      SPRING_CONFIG_ADDITIONAL_LOCATION: file:/app/application-default.yml
    volumes:
      - ./application-relations.yml:/app/application-default.yml
    restart: unless-stopped
    networks:
      - dockernet

networks:
  dockernet:
    external: true 
