services:
  message-exchange-api:
    image: ghcr.io/sundsvallskommun/api-service-message-exchange:latest
    container_name: message-exchange-api
    ports:
      - "8083:8080" 
    environment:
      SPRING_CONFIG_ADDITIONAL_LOCATION: file:/app/application-default.yml
    volumes:
      - ./application-message-exchange.yml:/app/application-default.yml
    restart: unless-stopped
    networks:
      - dockernet

networks:
  dockernet:
    external: true 
