services:
  party-api:
    image: ghcr.io/sundsvallskommun/api-service-party:latest
    ports:
      - "8089:8080" 
    environment:
      SPRING_CONFIG_ADDITIONAL_LOCATION: file:/app/application-default.yml
    volumes:
      - ./application-party.yml:/app/application-default.yml
    restart: unless-stopped
    networks:
      - dockernet

networks:
  dockernet:
    external: true 
