ARG NODE_VERSION=20-alpine

FROM node:${NODE_VERSION} AS deps
RUN apk add --no-cache libc6-compat git
WORKDIR /app
COPY package.json yarn.lock ./
RUN yarn install --frozen-lockfile --production=false

FROM node:${NODE_VERSION} AS builder
WORKDIR /app
COPY --from=deps /app/node_modules ./node_modules
COPY . .
ENV NEXT_TELEMETRY_DISABLED=1

RUN yarn dotenv -e .env.pt -- next build && \
    echo "=== Listar /app ===" && ls -la /app && \
    echo "=== Listar .next ===" && ls -la /app/.next || true

FROM node:${NODE_VERSION} AS runner
WORKDIR /app
ENV NODE_ENV=production
ENV NEXT_TELEMETRY_DISABLED=1

RUN addgroup --system nodejs && adduser --system nextjs
RUN ls -la /app

COPY --from=builder /app/public ./public
COPY --from=builder /app/package.json ./package.json
COPY --from=deps    /app/node_modules ./node_modules
COPY --from=builder /app/.next-PT ./.next

RUN ls -la /app
USER nextjs
EXPOSE 3000
ENV PORT=3000
CMD ["yarn", "start:pt"]
