spring:
  datasource:
    url: jdbc:mariadb://mariadb:3306/support_management
    username: support_management
    password: support_management
  jpa:
    hibernate:
    ddl-auto: validate
  flyway:
    enabled: true

  security:
    oauth2:
      client:
        provider:
          accessmapper:
            token-uri: http://wiremock:8080/token
          emailreader:
            token-uri: http://wiremock:8080/token
          employee:
            token-uri: http://wiremock:8080/token
          eventlog:
            token-uri: http://wiremock:8080/token
          messaging:
            token-uri: http://wiremock:8080/token
          messageexchange:
            token-uri: http://wiremock:8080/token
          messaging-settings:
            token-uri: http://wiremock:8080/token
          notes:
            token-uri: http://wiremock:8080/token
          web-message-collector:
            token-uri: http://wiremock:8080/token
          citizen:
            token-uri: http://wiremock:8080/token
          relation:
            token-uri: http://wiremock:8080/token
        registration:
          accessmapper:
            client-id: the-client-id
            client-secret: the-client-secret
          emailreader:
            client-id: the-client-id
            client-secret: the-client-secret
          employee:
            client-id: the-client-id
            client-secret: the-client-secret
          eventlog:
            client-id: the-client-id
            client-secret: the-client-secret
          messaging:
            client-id: the-client-id
            client-secret: the-client-secret
          messageexchange:
            client-id: the-client-id
            client-secret: the-client-secret
          messaging-settings:
            client-id: the-client-id
            client-secret: the-client-secret
          notes:
            client-id: the-client-id 
            client-secret: the-client-secret
          web-message-collector:
            client-id: the-client-id
            client-secret: the-client-secret
          citizen:
            client-id: the-client-id
            client-secret: the-client-secret
          relation:
            client-id: the-client-id
            client-secret: the-client-secret

integration:
  accessmapper:
    url: http://api-service-accessmapper:8080/
  emailreader:
    url: http://wiremock:8080/emailreader
  employee:
    url: http://wiremock:8080/employee
  eventlog:
    url: http://api-service-eventlog:8080/
  messaging:
    url: http://api-service-messaging:8080/
  messageexchange:
    url: http://api-service-messageexchange:8080/
  messaging-settings:
    url: http://api-service-messaging-settings:8080/
  notes:
    url: http://api-service-notes:8080/
  web-message-collector:
    url: http://wiremock:8080/webmessagecollector
  citizen:
    url: http://wiremock:8080/citizen
  relation:
    url: http://api-service-relations:8080/

scheduler:
  emailreader:
    cron: "-"
  web-message-collector:
    cron: "-"
  notification:
    cron: "-"
  messageexchange:
    cron: "-"
    enabled: false