spring:
  datasource:
    url: jdbc:mariadb://mariadb:3306/message_exchange
    username: message_exchange
    password: message_exchange
  jpa:
    hibernate:
    ddl-auto: validate
  flyway:
    enabled: true
