ARG NODE_VERSION=20.9.0-alpine
FROM node:${NODE_VERSION}

RUN apk add --no-cache libc6-compat

WORKDIR /app

COPY package.json yarn.lock ./
RUN yarn install --frozen-lockfile --ignore-scripts --prefer-offline

COPY . ./

RUN yarn build:kc

RUN addgroup --system --gid 1001 nodejs && adduser --system --uid 1001 nodejs

RUN mkdir -p /app/dist/logs && chown -R nodejs:nodejs /app

USER nodejs

ENV PORT=3001
EXPOSE 3001

CMD ["yarn", "start"]
