spring:
  datasource:
    url: jdbc:mariadb://mariadb:3306/email_reader
    username: email_reader
    password: email_reader
  jpa:
    hibernate:
    ddl-auto: validate
  flyway:
    enabled: true
integration: 
  messaging:
    base-url: http://messaging-api:8080/
    client-id: ignored
    client-secret: ignored
    token-uri: http://wiremock:8080/token

  