spring:
  datasource:
    url: jdbc:mariadb://mariadb:3306/web_message_collector
    username: web_message_collector
    password: web_message_collector
  jpa:
    hibernate:
    ddl-auto: validate
  flyway:
    enabled: true
  security:
    oauth2:
      client:
        provider:
          oep-integrator:
            token-uri: http://wiremock:8080/token
        registration:
          oep-integrator:
            authorization-grant-type: client_credentials
            provider: oep-integrator
            client-id: ignored
            client-secret: ignored
integration:
  oep-integrator:
    connect-timeout: 15
    read-timeout: 20
    url: http://oep-integrator-api:8080/
  open-e:
    environments:
      1984:
        scheduler:
          enabled: false 
          cron: "0 */15 * * * *"
          lock-at-most-for: PT2M
        internal:
          base-url: internal-base-url
          username: someInternalUsername
          password: someInternalPassword
          familyIds:
            - 123
            - 456