services:
  wiremock:
    image: wiremock/wiremock:3.6.0
    ports:
      - "9000:8080"
    volumes:
      - ./mappings:/home/wiremock/mappings
      - ./responses:/home/wiremock/__files
    environment:
      - JAVA_OPTS=-Dcom.github.tomakehurst.wiremock.global-response-templating=true
    command: ["--verbose"]
    networks:
      - dockernet

networks:
  dockernet:
    external: true 
